- hosts: all
  become: yes
  tasks:
   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present
   - name: install ca-certificates
     apt:
       name: ca-certificates
       state: present
   - name: install curl
     apt:
       name: curl
       state: present
   - name: install gnupg-agent
     apt:
       name: gnupg-agent
       state: present
   - name: software-properties-common
     apt:
       name: software-properties-common
       state: present
   - name: add docker apt-key 
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present      
   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'
   - name: add docker' APT repository
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
      filename: 'docker'
   - name: install Docker
     apt:
       name: docker-ce
       state: present
       update_cache: true
   - name: install Docker cli
     apt:
       name: docker-ce-cli
       state: present
       update_cache: true
   - name: install Docker containerd
     apt:
       name: containerd.io
       state: present
       update_cache: true
   - name: install kubelet
     apt:
       name: kubelet
       state: present
       update_cache: true
   - name: install kubeadm
     apt:
       name: kubeadm
       state: present
- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl
       state: present
       force: yes
